import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Banner from '../components/banner';
import Image from 'next/image';
import Card from '../components/card';

export default function Home() {
  const handleOnClick = () => {
    console.log('hi, banner button');
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connaisseur</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Banner buttonText={'Coffee Good!'} handleOnClick={handleOnClick} />
        <div className={styles.heroImage}>
          <Image src='/static/hero-image.png' height={400} width={1000} />
        </div>
        <Card name='DarkHorse Cofee' imageUrl='/static/hero-image.png' href='/coffee-store/darkhorse-coffee' />
      </main>
    </div>
  );
}
